# Generated by Django 3.1.7 on 2021-05-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='degree',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='school',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='other_info',
        ),
    ]
