# Generated by Django 3.1.7 on 2021-05-08 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210507_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('portfolio', models.CharField(max_length=100)),
                ('clg', models.CharField(max_length=100)),
                ('clg_cg', models.CharField(max_length=100)),
                ('start_clg', models.CharField(max_length=100)),
                ('end_clg', models.CharField(max_length=100)),
                ('edu', models.CharField(max_length=100)),
                ('edu_cg', models.CharField(max_length=100)),
                ('start_edu', models.CharField(max_length=100)),
                ('end_edu', models.CharField(max_length=100)),
                ('exp1', models.CharField(max_length=100)),
                ('start_exp1', models.CharField(max_length=100)),
                ('end_exp1', models.CharField(max_length=100)),
                ('exp2', models.CharField(max_length=100)),
                ('start_exp2', models.CharField(max_length=100)),
                ('end_exp2', models.CharField(max_length=100)),
                ('exp3', models.CharField(max_length=100)),
                ('start_exp3', models.CharField(max_length=100)),
                ('end_exp3', models.CharField(max_length=100)),
                ('pj1', models.CharField(max_length=100)),
                ('start_pg1', models.CharField(max_length=100)),
                ('end_pg1', models.CharField(max_length=100)),
                ('pj2', models.CharField(max_length=100)),
                ('start_pg2', models.CharField(max_length=100)),
                ('end_pg2', models.CharField(max_length=100)),
                ('pj3', models.CharField(max_length=100)),
                ('start_pg3', models.CharField(max_length=100)),
                ('end_pg3', models.CharField(max_length=100)),
                ('Achievments', models.TextField(max_length=10000)),
                ('Skills', models.TextField(max_length=10000)),
                ('Por', models.TextField(max_length=10000)),
                ('Hobbies', models.TextField(max_length=10000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
