# Generated by Django 3.1.7 on 2021-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210508_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='other_info',
            field=models.TextField(default=None, max_length=10000),
        ),
    ]
