# Generated by Django 3.1.7 on 2021-05-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_info_other_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Hobbies',
            new_name='Hobbie',
        ),
    ]
