# Generated by Django 3.1.7 on 2021-05-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210508_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='end_pg1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='start_pg1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
