# Generated by Django 3.1.7 on 2021-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210508_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='exp1_info',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
